[build]
  command = "npm run build:all"
  publish = "frontend/.next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
