[build]
  command = "npm run build:all"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  NEXT_PRIVATE_TARGET = "server"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200