[build]
  command = "npm run build:all"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
