[build]
  command = "npm run build:all"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.12.6"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200